services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=${REDIS_PASS}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - postgresql
    networks:
      - postgres

  postgresql:
    image: postgres:17.4-alpine
    restart: always
    ports:
      - 15432:5432
    networks:
      - postgres
    volumes:
      - ${DATA_PATH}/postgres/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}

  pgadmin:
    image: dpage/pgadmin4
    privileged: true
    ports:
      - 15433:80
    depends_on:
      - postgresql
    networks:
      - postgres
    volumes:
      - ${DATA_PATH}/pgadmin/:/var/lib/pgadmin/
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_DEFAULT_PASS}

networks:
  postgres:
    driver: bridge
