services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=${REDIS_PASS}
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "info", "memory", "|", "grep", "used_memory:"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS}
    

volumes:
  redis_data:

networks:
  backend:
    driver: bridge